// const http = uni.$u.http

// export const post = (url,params) => http.post(url,params)
// export const get = (url,params) =>  http.get(url,params)
// export const put = (url,params) => http.put(url,params)
// export const del = (url,params) => http.delete(url,params)
// export const upload = (url,params) => http.upload(url,params)
// export const download = (url,params) => http.download(url,params)
// export const request = (url,params) => http.request(url,params)
// export const requestAll = (params) => http.requestAll(params)
// export const requestAllWithToken = (params) => http.requestAllWithToken(params)
// export const requestAllWithTokenAndLoading = (params) => http.requestAllWithTokenAndLoading(params)
// export const requestWithToken = (url,params) => http.requestWithToken(url,params)
// export const requestWithTokenAndLoading = (url,params) => http.requestWithTokenAndLoading(url,params)
// export const requestWithLoading = (url,params) => http.requestWithLoading(url,params)
// export const requestWithTokenAndLoadingAndToast = (url,params) => http.requestWithTokenAndLoadingAndToast(url,params)
// export const requestWithTokenAndToast = (url,params) => http.requestWithTokenAndToast(url,params)
// export const requestWithLoadingAndToast = (url,params) => http.requestWithLoadingAndToast(url,params)
// export const requestWithToast = (url,params) => http.requestWithToast(url,params)
// export const requestWithTokenAndLoadingAndToastAndError = (url,params) => http.requestWithTokenAndLoadingAndToastAndError(url,params)
// export const requestWithTokenAndToastAndError = (url,params) => http.requestWithTokenAndToastAndError(url,params)
// export const requestWithLoadingAndToastAndError = (url,params) => http.requestWithLoadingAndToastAndError(url,params)
// export const requestWithToastAndError = (url,params) => http.requestWithToastAndError(url,params)
// export const requestWithTokenAndLoadingAndToastAndErrorAndCatch = (url,params) => http.requestWithTokenAndLoadingAndToastAndErrorAndCatch(url,params)
